apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-sa
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-role
rules:
  - apiGroups: ["", "apps","networking.k8s.io"]
    resources: ["deployments","services","configmaps","persistentvolumes","persistentvolumeclaims","networkpolicies"]
    verbs: ["create", "get", "list", "watch", "update"]
  - apiGroups: ["ashwin901.operators"]
    resources: ["socialbooks"]
    verbs: ["get","list", "watch"]
  - apiGroups: ["ashwin901.operators"]
    resources: ["socialbooks/status"]
    verbs: ["update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-rb
subjects:
  - kind: ServiceAccount
    name: operator-sa
    namespace: dev
roleRef:
  kind: ClusterRole
  name: operator-role
  apiGroup: rbac.authorization.k8s.io