/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	operatorsv1alpha1 "github.com/ashwin901/social-book-operator/pkg/apis/operators/v1alpha1"
	versioned "github.com/ashwin901/social-book-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/ashwin901/social-book-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/ashwin901/social-book-operator/pkg/client/listers/operators/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SocialBookInformer provides access to a shared informer and lister for
// SocialBooks.
type SocialBookInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.SocialBookLister
}

type socialBookInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSocialBookInformer constructs a new informer for SocialBook type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSocialBookInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSocialBookInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSocialBookInformer constructs a new informer for SocialBook type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSocialBookInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OperatorsV1alpha1().SocialBooks(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OperatorsV1alpha1().SocialBooks(namespace).Watch(context.TODO(), options)
			},
		},
		&operatorsv1alpha1.SocialBook{},
		resyncPeriod,
		indexers,
	)
}

func (f *socialBookInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSocialBookInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *socialBookInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&operatorsv1alpha1.SocialBook{}, f.defaultInformer)
}

func (f *socialBookInformer) Lister() v1alpha1.SocialBookLister {
	return v1alpha1.NewSocialBookLister(f.Informer().GetIndexer())
}
