/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/ashwin901/social-book-operator/pkg/apis/ashwin901.operators/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSocialBooks implements SocialBookInterface
type FakeSocialBooks struct {
	Fake *FakeOperatorsV1alpha1
	ns   string
}

var socialbooksResource = schema.GroupVersionResource{Group: "operators", Version: "v1alpha1", Resource: "socialbooks"}

var socialbooksKind = schema.GroupVersionKind{Group: "operators", Version: "v1alpha1", Kind: "SocialBook"}

// Get takes name of the socialBook, and returns the corresponding socialBook object, and an error if there is any.
func (c *FakeSocialBooks) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SocialBook, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(socialbooksResource, c.ns, name), &v1alpha1.SocialBook{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SocialBook), err
}

// List takes label and field selectors, and returns the list of SocialBooks that match those selectors.
func (c *FakeSocialBooks) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SocialBookList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(socialbooksResource, socialbooksKind, c.ns, opts), &v1alpha1.SocialBookList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SocialBookList{ListMeta: obj.(*v1alpha1.SocialBookList).ListMeta}
	for _, item := range obj.(*v1alpha1.SocialBookList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested socialBooks.
func (c *FakeSocialBooks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(socialbooksResource, c.ns, opts))

}

// Create takes the representation of a socialBook and creates it.  Returns the server's representation of the socialBook, and an error, if there is any.
func (c *FakeSocialBooks) Create(ctx context.Context, socialBook *v1alpha1.SocialBook, opts v1.CreateOptions) (result *v1alpha1.SocialBook, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(socialbooksResource, c.ns, socialBook), &v1alpha1.SocialBook{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SocialBook), err
}

// Update takes the representation of a socialBook and updates it. Returns the server's representation of the socialBook, and an error, if there is any.
func (c *FakeSocialBooks) Update(ctx context.Context, socialBook *v1alpha1.SocialBook, opts v1.UpdateOptions) (result *v1alpha1.SocialBook, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(socialbooksResource, c.ns, socialBook), &v1alpha1.SocialBook{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SocialBook), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSocialBooks) UpdateStatus(ctx context.Context, socialBook *v1alpha1.SocialBook, opts v1.UpdateOptions) (*v1alpha1.SocialBook, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(socialbooksResource, "status", c.ns, socialBook), &v1alpha1.SocialBook{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SocialBook), err
}

// Delete takes name of the socialBook and deletes it. Returns an error if one occurs.
func (c *FakeSocialBooks) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(socialbooksResource, c.ns, name, opts), &v1alpha1.SocialBook{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSocialBooks) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(socialbooksResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.SocialBookList{})
	return err
}

// Patch applies the patch and returns the patched socialBook.
func (c *FakeSocialBooks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SocialBook, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(socialbooksResource, c.ns, name, pt, data, subresources...), &v1alpha1.SocialBook{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SocialBook), err
}
